language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t javascratches/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javascratches/multi-client-test npm run test -- --watchAll=false

after_success:
  - docker build -t javascratches/multi-client ./client
  - docker build -t javascratches/multi-nginx ./nginx
  - docker build -t javascratches/multi-server ./server
  - docker build -t javascratches/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push javascratches/multi-client  
  - docker push javascratches/multi-nginx  
  - docker push javascratches/multi-server  
  - docker push javascratches/multi-worker
  




