language: generic

sudo: required
services: 
  - docker

before_install:
  - docker build -t javascratches/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javascratches/multi-client-test npm run test -- --watchAll=false

after_success:
  - docker build -t javascratches/multi-client ./client
  - docker build -t javascratches/multi-nginx ./nginx
  - docker build -t javascratches/multi-server ./server
  - docker build -t javascratches/multi-worker ./worker


# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "wklej
#   bucket_name: "wklej"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"
